export default {
  pages: [
    'pages/index/index',
    'pages/button/index',
    'pages/cell/index',
    'pages/icon/index',
    'pages/image/index',
    'pages/layout/index',
    'pages/popup/index',
    'pages/style/index',
    'pages/toast/index',
    'pages/badge/index',
    'pages/collapse/index',
    'pages/countdown/index',
    'pages/divider/index',
    'pages/empty/index',
    'pages/notice-bar/index',
    'pages/skeleton/index',
    'pages/steps/index',
    'pages/tag/index',
    'pages/grid/index',
    'pages/nav-bar/index',
    'pages/pagination/index',
    'pages/sidebar/index',
    'pages/tab/index',
    'pages/tabbar/index',
    'pages/tree-select/index',
    'pages/cascader/index',
    'pages/action-sheet/index',
    'pages/dialog/index',
    'pages/loading/index',
    'pages/overlay/index',
    'pages/share-sheet/index',
    'pages/rate/index',
    'pages/checkbox/index',
    'pages/field/index',
    'pages/form/index',
    'pages/radio/index',
    'pages/search/index',
    'pages/stepper/index',
    'pages/number-keyboard/index',
    'pages/password-input/index',
    'pages/address-list/index',
    'pages/card/index',
    'pages/contact-card/index',
    'pages/contact-list/index',
    'pages/goods-action/index',
    'pages/submit-bar/index',
    'pages/coupon/index'
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  }
}
